### PR TITLE
Bug 1948513: Add support for no_proxy

### LINKED ISSUE #38: get-resources.sh doesn't honor the no_proxy settings
https://github.com/openshift/ironic-rhcos-downloader/blob/384a3fe99ee90a627563647a7b03de47dc45d314/get-resource.sh#L5

In proxy environments, it is always needed to use the http_proxy, https_proxy and the no_proxy variable, otherwise if you want to reach internal resources you will be using the proxy which may not work.

### PR DESCRIPTION
**Pull request by e-minguez**
Fix #38

### CODE REVIEW

**Review by elfosardo — APPROVED** [review]

**Comment by e-minguez** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1948513

**Comment by e-minguez** [comment]
/retitle Bug 1948513: Add support for no_proxy

**Pull request merged**
