### PR TITLE
If RHCOS image is gzipped, decompress first before passing to qemu-img

### PR DESCRIPTION
**Pull request by stbenjam**
The latest RHCOS image in openshift/install is pointing to gzipped
images. We need to make the coreos-downloader aware of that.

### CODE REVIEW

**Comment by stbenjam** [comment]
At the moment bootstrap isn't even coming up as it's also gzipped. Investigating that now...

**Comment by hardys** [comment]
I worked around the bootstrap issue and AFAICS this is working fine, however we'll need additional fixes to the installer to make the deployment work as it now fails like:

```
level=error msg="Error: Bad request with: [PUT http://172.22.0.2:6385/v1/nodes/2e4048b2-6e1d-4812-9854-df4f5d4a7fcd/states/provision], error message: {\"error_message\": \"{\\\"faultcode\\\": \\\"Client\\\", \\\"faultstring\\\": \\\"Failed to validate deploy or power info for node 2e4048b2-6e1d-4812-9854-df4f5d4a7fcd. Error: Validation of image href http://172.22.0.2/images/rhcos-43.81.201911081536.0-openstack.x86_64.qcow2.gz/rhcos-43.81.201911081536.0-compressed.x86_64.qcow2.gz failed, reason: Got HTTP code 404 instead of 200 in response to HEAD request.\\\", \\\"debuginfo\\\": null}\"}"
```

**Pull request merged**
